"use client";
function discussion() {
    return (
        <div className="flex flex-col">
            <h1>Discussion</h1>
            <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1> <h1>Discussion</h1>
        </div>
    )
}
export default discussion;