export type IconsType =
  | 'learn'
  | '10'
  | 'dashboard'
  | 'settings.svg'
  | 'community'
  | 'Analytics'
  | 'profile'
  | 'purchase'
  | 'profile-voilet'
  | 'collapse-left'
  | 'collapse-right'
  | 'Name'
  | 'Email'
  | 'phoneNumber'
  | 'TargetYear'
  | 'pencil-edit'
  | 'CopyButton';