export type IconsType =
  | 'learn'
  | '10'
  | 'dashboard'
  | 'settings'
  | 'community'
  | 'Analytics'
  | 'learn-2'
  | 'dashboard-2'
  | 'settings-2'
  | 'community-2'
  | 'Analytics-2'
  | 'profile'
  | 'purchase'
  | 'profile-voilet'
  | 'collapse-left'
  | 'collapse-right'
  | 'Name'
  | 'Email'
  | 'phoneNumber'
  | 'TargetYear'
  | 'pencil-edit'
  | 'CopyButton'
  | 'no_announcement_img'
  | 'course_img'
  | 'suggestion_icon'
  | 'overall'
  | 'maths'
  | 'physics'
  | 'chemistry'
  | 'checkmark'
  | 'announceProfile'
  | 'right'
  | 'course-left'
  | 'read'
  | 'vedio'
  | 'test'
  | 'up'
  | 'sidebuttongray'
  | 'sidebuttonrred'
  | "Green-tick"
  | "clock"
  | "questionmark"
  | "check-list"
  | "alram-clock"
  | "arrowdown"
  | "arrowup"
  | "profile-pic"
  | "upvote"
  | "Bold-icon"
  | "italic-icon"
  | "underline-icon"
  | "dropdown-icon-1"
  | "dropdown-icon-2"
  | "dropdown-icon-3"
  | "align-left"
  | "align-right"
  | "align-middle"

  | "QuestionMark"
  | "right-arrow"
  | "full-star"
  | "half-star"
  | "empty-star"
  | "Re-attempt"
  | "correct"
  | "incorrect"
  | "overal"
  | "information-circle"
  | "unanswered"
  | "QuizTalk"
  | "MathsQuicktest"
  | "studymaterial.png"
  | "PhyiscsQuicktest"
  | "ChemistryQuicktest"
  | "MathsQuicktest.png"
  | "details"
  | "sendCommunity"
  | "image"
  | "video-icon"
  | "documents"
  | "Media-Images"
  | "Media-No-Videos"
  | "Media-No-Documents"
  | "Media-No-Links"
  | "profile-pic2"
  | "arrow-down"
  | "smile"
  | "Reply"
  | "copy"
  | "Bookmark"
  | "Report"
  | "plus-icon"
  | "emoji-1"
  | "emoji-2"
  | "emoji-3"
  | "emoji-4"
  | "emoji-5"
  | "profile-3"
  | "profile-4"
  | "search-button"
  | "selectdate-Arrowdown"
  | "three-dots"
  | "Saved"
  | "Live"
  | "secheduled"
  | "Paused"
  | "Finished"
  | "cancelled"
  | "input"
  | "upload-cloud"
  | "three-double-dots"
  | "tick-02"
  | "duplicate"
  | "delete"
  | "uploadcheckmark"
  | "publish-quiz"
  | "expandall"
  | "endquiz"
  | "pausequiz"
  | "resume"
  | "collaspe-all";






