export type IconsType =
  | 'learn'
  | '10'
  | 'dashboard'
  | 'settings'
  | 'community'
  | 'Analytics'
  | 'learn-2'
  | 'dashboard-2'
  | 'settings-2'
  | 'community-2'
  | 'Analytics-2'
  | 'profile'
  | 'purchase'
  | 'profile-voilet'
  | 'collapse-left'
  | 'collapse-right'
  | 'Name'
  | 'Email'
  | 'phoneNumber'
  | 'TargetYear'
  | 'pencil-edit'
  | 'CopyButton'
  | 'no_announcement_img'
  | 'course_img'
  | 'suggestion_icon'
  | 'overall'
  | 'maths'
  | 'physics'
  | 'chemistry'
  | 'checkmark'
  | 'announceProfile'
  | 'right'
  | 'course-left'
  | 'read'
  | 'vedio'
  | 'test'
  | 'up'
  | 'sidebuttongray'
  | 'sidebuttonrred'
  | "Green-tick"
  | "clock"
  | "questionmark"
  | "check-list"
  | "alram-clock"
  | "arrowdown"
  | "arrowup"
  | "profile-pic"
  | "upvote"
  | "Bold-icon"
  | "italic-icon"
  | "underline-icon"
  | "dropdown-icon-1"
  | "dropdown-icon-2"
  | "dropdown-icon-3"
  | "align-left"
  | "align-right"
  | "align-middle"
  | "edit-02"
  | "questionmark"
  | "right-arrow"
  | "full-star"
  | "half-star"
  | "empty-star"
  | "Re-attempt"
  | "correct"
  | "incorrect"
  | "overal"
  | "information-circle"
  | "unanswered"
  | "QuizTalk"
  | "MathsQuicktest"
  | "studymaterial.png"
  | "PhyiscsQuicktest"
  | "ChemistryQuicktest"
  | "MathsQuicktest.png"
  | "details"
  | "sendCommunity"
  | "image"
  | "video-icon"
  | "documents"
  | "Media-Images"
  | "Media-No-Videos"
  | "Media-No-Documents"
  | "Media-No-Links"
  | "profile-pic2"
  | "arrow-down"
  | "smile"
  | "Reply"
  | "copy"
  | "Bookmark"
  | "Report"
  | "plus-icon"
  | "emoji-1"
  | "emoji-2"
  | "emoji-3"
  | "emoji-4"
  | "emoji-5"
  | "profile-3"
  | "profile-4"
  | "search-button"
  | "selectdate-Arrowdown"
  | "three-dots"
  | "Saved"
  | "Live"
  | "secheduled"
  | "Paused"
  | "Finished"
  | "cancelled"
  | "input"
  | "upload-cloud"
  | "three-double-dots"
  | "tick-02"
  | "duplicate"
  | "delete"
  | "uploadcheckmark"
  | "publish-quiz"
  | "expandall"
  | "endquiz"
  | "pausequiz"
  | "resume"
  | "collaspe-all"
  | "plus-sign"
  | "clock-01"
  | "colorless-star"
  | "pdf-icon"
  | "Role Management"
  | "Role Management-2"
  | "Marketing Integration"
  | "Marketing Integration-2"
  | "by-role-arrow-down"
  | "logout-03"
  | "big-profile-pic"
  | "chevron-down"
  | "megaphone"
  | "read-2"
  | "idea-2"
  | "elements (3)"
  | "Arrow-up"
  | "Arrow-down-1"
  | "resume-2"
  | "internal-chat-1"
  | "internal-chat-2"
  | "discussion-form"
  | "discussion-form-2"
  | "arrow-up-dark"
  | "arrow-down-dark"
  | "arrow-right-01-round"
  | "plus-dark"
  | "communityicon"
  | "mark as read"
  | "mute"
  | "media"
  | "channel-requests"
  | "Create-category"
  | "upload-icon"
  | "arrow-dark-down-1"
  | "green-color-umute"
  | "comment-icon"
  | "unpin-icon"
  | "pin-icon"
  | "chevron-down-dark-1"
  | "link-icon"
  | "upload-image-icon"
  | "coma"
  | "download-reciepts"
  | "Download Invoice"
  | "quiz-02"
  | "right-mark"
  | 'red-cancel-icon'
  | "green-right-mark"
  | "community-pink-color"
  | "collaspeDetails-2"
  | "Subject Chapters-1"
  | "Subject Chapters-2"
  | "plus-white-sign"
  | "exit-channel-red"
  | "arrow-up-01-round(2)-white"
  | "arrow-down-01-round(2)-white"
  | "white-arrow-up";







