import SideButton from "@/components/DashboardComponents/LearnComponents/CourseComponents/InsideCoursesComp/SideButton";
function sidebutton() {
    return (
        <div className="flex flex-row w-screen" >
        <div className="MainCourseLayout flex flex-col w-[80%] bg-slate-700 overflow-y-auto p-3">
         <h3>Courses...Bitsat</h3>
         <div className="flex flex-col w-[300px] h-auto text-white bg-black">
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>
          <h3>Hello</h3>

         </div>
        </div>
        <div className="SideLayout w-[20%] flex flex-col bg-red-500 overflow-y-auto p-3">
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>
        <p>Side..........</p>

        </div>

        </div>
    )
}
export default sidebutton;