
function sidebutton() {
    return (
        <div className="flex flex-row w-screen" >
            <div className="MainCourseLayout flex flex-col w-[80%] bg-slate-700 overflow-y-auto p-3">
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
            </div>
            <div className="SideLayout w-[20%] flex flex-col bg-red-500 overflow-y-auto p-3">
                <div className="bg-green-500 w-[331px] h-[64px] gap-[16px] ">

                </div>


            </div>

        </div>
    )
}
export default sidebutton;