
function sidebutton() {
    return (
        <div className="flex flex-row w-screen" >
            <div className="MainCourseLayout flex flex-col w-[68.92%] bg-slate-700 overflow-y-auto p-3">
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
                <h3>Main..........</h3>
            </div>
            <div className="SideLayout w-[31.08%] flex flex-col bg-[#FFFFFF] overflow-y-auto p-3">
                <div className="bg-[#F8F0FF] h-[64px] gap-[16px] rounded-[8px]">
                    <button>
                        <span></span>
                    </button>

                </div>



            </div>

        </div>
    )
}
export default sidebutton;